import {
  pgTable,
  uuid,
  text,
  integer,
  real,
  boolean,
  jsonb,
  timestamp,
} from "drizzle-orm/pg-core";

export const jeeps = pgTable("jeeps", {
  id: uuid("id").primaryKey().defaultRandom(),
  slug: text("slug").unique().notNull(),
  nama: text("nama").notNull(),
  harga: integer("harga").notNull(),
  rating: real("rating").default(0),
  ulasan: integer("ulasan").default(0),
  maksOrang: integer("maks_orang"),
  durasi: text("durasi"),
  destinasiCount: integer("destinasi_count"),
  deskripsi: text("deskripsi"),
  fotoUtama: text("foto_utama"),
  galeri: jsonb("galeri").default([]),
  destinasi: jsonb("destinasi").default([]),
  isiPaket: jsonb("isi_paket").default([]),
  kebijakan: jsonb("kebijakan").default([]),
  bookedDates: jsonb("booked_dates").default([]),
  whatsappOwner: text("whatsapp_owner"),
  isActive: boolean("is_active").default(true),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});
